-- ============================================================
-- ConstructManager — Full Database Deployment
-- Generated by scripts/combine-sql.py
-- Run this entire file in Supabase SQL Editor to deploy
-- the complete database schema, RLS policies, storage,
-- functions, and seed data.
-- ============================================================

-- ============================================================
-- 001-schema.sql
-- ============================================================

-- ============================================================
-- ConstructManager — Full Database Schema for Supabase
-- Apply in order: 001 → 002 → 003 → 004
-- ============================================================

-- ******************** USERS ********************
CREATE TABLE IF NOT EXISTS users (
    uid TEXT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL UNIQUE,
    admin BOOLEAN NOT NULL DEFAULT FALSE,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    role TEXT NOT NULL DEFAULT 'executor' CHECK (role IN ('executor', 'customer', 'contractor')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ******************** CONSTRUCTIONS ********************
CREATE TABLE IF NOT EXISTS constructions (
    uid TEXT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    type TEXT NOT NULL DEFAULT '',
    stage TEXT NOT NULL DEFAULT 'ПОДГОТОВКА' CHECK (stage IN ('ПОДГОТОВКА', 'В_ИСПОЛНЕНИИ', 'ОТМЕНЕНО', 'ЗАВЕРШЕНО')),
    responsibles JSONB NOT NULL DEFAULT '[]'::jsonb,
    owner_uid TEXT NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
    map_address TEXT NOT NULL DEFAULT '',
    information TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    budget REAL
);

CREATE INDEX IF NOT EXISTS idx_constructions_owner ON constructions(owner_uid);
CREATE INDEX IF NOT EXISTS idx_constructions_stage ON constructions(stage);
CREATE INDEX IF NOT EXISTS idx_constructions_created ON constructions(created_at DESC);

-- ******************** BUDGETS ********************
CREATE TABLE IF NOT EXISTS budgets (
    uid TEXT PRIMARY KEY,
    construction_uid TEXT NOT NULL REFERENCES constructions(uid) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    value REAL NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_budgets_construction ON budgets(construction_uid);

-- ******************** SCHEDULES ********************
CREATE TABLE IF NOT EXISTS schedules (
    uid TEXT PRIMARY KEY,
    construction_uid TEXT NOT NULL REFERENCES constructions(uid) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT '',
    start_date TEXT,
    deadline TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL DEFAULT 'ON_SCHEDULE' CHECK (state IN ('ON_SCHEDULE', 'LATE', 'SOLVED')),
    finish_date TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_schedules_construction ON schedules(construction_uid);

ALTER TABLE schedules ADD COLUMN IF NOT EXISTS start_date TEXT;

-- ******************** DELAYS ********************
CREATE TABLE IF NOT EXISTS delays (
    uid TEXT PRIMARY KEY,
    construction_uid TEXT NOT NULL REFERENCES constructions(uid) ON DELETE CASCADE,
    schedule_uid TEXT NOT NULL REFERENCES schedules(uid) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT '',
    is_excusable BOOLEAN NOT NULL DEFAULT FALSE,
    is_compensable BOOLEAN NOT NULL DEFAULT FALSE,
    is_concurrent BOOLEAN NOT NULL DEFAULT FALSE,
    is_critical BOOLEAN NOT NULL DEFAULT FALSE,
    days INT NOT NULL DEFAULT 0,
    additional_info TEXT NOT NULL DEFAULT '',
    finished BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_delays_construction ON delays(construction_uid);
CREATE INDEX IF NOT EXISTS idx_delays_schedule ON delays(schedule_uid);

-- ******************** RESPONSIBILITIES (removed) ********************

-- ******************** PHOTOS ********************
CREATE TABLE IF NOT EXISTS photos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    uid TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    construction_uid TEXT NOT NULL REFERENCES constructions(uid) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    file_size BIGINT,
    mime_type TEXT DEFAULT 'image/jpeg',
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_photos_construction ON photos(construction_uid);
CREATE INDEX IF NOT EXISTS idx_photos_uid ON photos(uid);

-- ============================================================
-- 002-rls.sql
-- ============================================================

-- ============================================================
-- ConstructManager — Row Level Security Policies
-- Run after 001-schema.sql
-- ============================================================

-- ******************** USERS ********************
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read users" ON users;
CREATE POLICY "Anyone can read users"
    ON users FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Users can insert own record" ON users;
CREATE POLICY "Users can insert own record"
    ON users FOR INSERT
    TO authenticated
    WITH CHECK (uid = auth.uid()::text);

DROP POLICY IF EXISTS "Users can update own record" ON users;
CREATE POLICY "Users can update own record"
    ON users FOR UPDATE
    TO authenticated
    USING (uid = auth.uid()::text);

-- ******************** CONSTRUCTIONS ********************
ALTER TABLE constructions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read their constructions" ON constructions;
CREATE POLICY "Users can read their constructions"
    ON constructions FOR SELECT
    TO authenticated
    USING (owner_uid = auth.uid()::text);

DROP POLICY IF EXISTS "Users can insert their constructions" ON constructions;
CREATE POLICY "Users can insert their constructions"
    ON constructions FOR INSERT
    TO authenticated
    WITH CHECK (owner_uid = auth.uid()::text);

DROP POLICY IF EXISTS "Users can update their constructions" ON constructions;
CREATE POLICY "Users can update their constructions"
    ON constructions FOR UPDATE
    TO authenticated
    USING (owner_uid = auth.uid()::text);

DROP POLICY IF EXISTS "Users can delete their constructions" ON constructions;
CREATE POLICY "Users can delete their constructions"
    ON constructions FOR DELETE
    TO authenticated
    USING (owner_uid = auth.uid()::text);

-- ******************** BUDGETS ********************
ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read budgets of their constructions" ON budgets;
CREATE POLICY "Users can read budgets of their constructions"
    ON budgets FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = budgets.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can insert budgets" ON budgets;
CREATE POLICY "Users can insert budgets"
    ON budgets FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = budgets.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can update budgets" ON budgets;
CREATE POLICY "Users can update budgets"
    ON budgets FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = budgets.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can delete budgets" ON budgets;
CREATE POLICY "Users can delete budgets"
    ON budgets FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = budgets.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

-- ******************** SCHEDULES ********************
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read schedules of their constructions" ON schedules;
CREATE POLICY "Users can read schedules of their constructions"
    ON schedules FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = schedules.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can insert schedules" ON schedules;
CREATE POLICY "Users can insert schedules"
    ON schedules FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = schedules.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can update schedules" ON schedules;
CREATE POLICY "Users can update schedules"
    ON schedules FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = schedules.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can delete schedules" ON schedules;
CREATE POLICY "Users can delete schedules"
    ON schedules FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = schedules.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

-- ******************** DELAYS ********************
ALTER TABLE delays ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read delays of their constructions" ON delays;
CREATE POLICY "Users can read delays of their constructions"
    ON delays FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = delays.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can insert delays" ON delays;
CREATE POLICY "Users can insert delays"
    ON delays FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = delays.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can update delays" ON delays;
CREATE POLICY "Users can update delays"
    ON delays FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = delays.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can delete delays" ON delays;
CREATE POLICY "Users can delete delays"
    ON delays FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = delays.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

-- ******************** RESPONSIBILITIES ********************
ALTER TABLE responsabilities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read responsibilities of their constructions" ON responsabilities;
CREATE POLICY "Users can read responsibilities of their constructions"
    ON responsabilities FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = responsabilities.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can insert responsibilities" ON responsabilities;
CREATE POLICY "Users can insert responsibilities"
    ON responsabilities FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = responsabilities.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can update responsibilities" ON responsabilities;
CREATE POLICY "Users can update responsibilities"
    ON responsabilities FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = responsabilities.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can delete responsibilities" ON responsabilities;
CREATE POLICY "Users can delete responsibilities"
    ON responsabilities FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = responsabilities.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

-- ******************** PHOTOS ********************
ALTER TABLE photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read photos of their constructions" ON photos;
CREATE POLICY "Users can read photos of their constructions"
    ON photos FOR SELECT
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = photos.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can insert photos" ON photos;
CREATE POLICY "Users can insert photos"
    ON photos FOR INSERT
    TO authenticated
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = photos.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can update photos" ON photos;
CREATE POLICY "Users can update photos"
    ON photos FOR UPDATE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = photos.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

DROP POLICY IF EXISTS "Users can delete photos" ON photos;
CREATE POLICY "Users can delete photos"
    ON photos FOR DELETE
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM constructions
            WHERE constructions.uid = photos.construction_uid
            AND constructions.owner_uid = auth.uid()::text
        )
    );

-- ============================================================
-- 003-storage.sql
-- ============================================================

-- ============================================================
-- ConstructManager — Supabase Storage Setup
-- Run after 002-rls.sql
-- 1. Create bucket manually in Supabase Dashboard OR via API
-- 2. Run this SQL for bucket policies
-- ============================================================

-- Ensure the bucket exists (run CREATE or use Dashboard)
INSERT INTO storage.buckets (id, name, public)
VALUES ('construction-photos', 'construction-photos', true)
ON CONFLICT (id) DO NOTHING;

-- Function to create bucket from the app (called via anon key + RPC)
CREATE OR REPLACE FUNCTION create_photo_bucket()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO storage.buckets (id, name, public)
  VALUES ('construction-photos', 'construction-photos', true)
  ON CONFLICT (id) DO NOTHING;
END;
$$;

-- Allow authenticated users to call this function
GRANT EXECUTE ON FUNCTION create_photo_bucket() TO authenticated;

-- ******************** STORAGE POLICIES ********************

-- Allow authenticated users to upload photos
DROP POLICY IF EXISTS "authenticated_upload_photos" ON storage.objects;
CREATE POLICY "authenticated_upload_photos"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'construction-photos'
);

-- Allow public access to view photos
DROP POLICY IF EXISTS "public_view_photos" ON storage.objects;
CREATE POLICY "public_view_photos"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'construction-photos');

-- Allow authenticated users to update photos
DROP POLICY IF EXISTS "authenticated_update_photos" ON storage.objects;
CREATE POLICY "authenticated_update_photos"
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'construction-photos');

-- Allow authenticated users to delete their photos
DROP POLICY IF EXISTS "authenticated_delete_photos" ON storage.objects;
CREATE POLICY "authenticated_delete_photos"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'construction-photos');

-- ******************** VERIFICATION ********************
SELECT
    'Storage policies created' as status,
    COUNT(*) as policy_count
FROM pg_policies
WHERE tablename = 'objects'
AND schemaname = 'storage';

-- ============================================================
-- 004-functions.sql
-- ============================================================

-- ============================================================
-- ConstructManager — Helper Functions & Triggers
-- Run after 002-rls.sql
-- ============================================================

-- ******************** AUTO-CREATE USER ON SIGNUP ********************
-- Trigger: when a new user signs up via Supabase Auth,
-- automatically create a matching record in the public.users table.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.users (uid, name, email, admin, is_email_verified, role)
    VALUES (
        NEW.id::text,
        COALESCE(NEW.raw_user_meta_data ->> 'name', split_part(NEW.email, '@', 1)),
        NEW.email,
        FALSE,
        COALESCE(NEW.email_confirmed_at IS NOT NULL, FALSE),
        COALESCE(NEW.raw_user_meta_data ->> 'role', 'executor')
    )
    ON CONFLICT (uid) DO UPDATE SET
        email = EXCLUDED.email,
        is_email_verified = COALESCE(NEW.email_confirmed_at IS NOT NULL, FALSE);
    RETURN NEW;
END;
$$;

-- Apply trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- Also update on email verification
DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
    AFTER UPDATE OF email_confirmed_at ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- ******************** CONSTRUCTION STAGE HELPER ********************
CREATE OR REPLACE FUNCTION public.get_stage_display(stage TEXT)
RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
AS $$
    SELECT CASE stage
        WHEN 'ПОДГОТОВКА'  THEN 'Preparation'
        WHEN 'В_ИСПОЛНЕНИИ' THEN 'In Progress'
        WHEN 'ОТМЕНЕНО'    THEN 'Cancelled'
        WHEN 'ЗАВЕРШЕНО'   THEN 'Finished'
        ELSE stage
    END;
$$;

-- ******************** BUDGET TOTALS ********************
CREATE OR REPLACE FUNCTION public.get_construction_budget_total(construction_uid TEXT)
RETURNS REAL
LANGUAGE SQL
STABLE
AS $$
    SELECT COALESCE(SUM(value), 0)
    FROM public.budgets
    WHERE budgets.construction_uid = $1;
$$;

-- ******************** AUTO-UPDATE CONSTRUCTION BUDGET ********************
CREATE OR REPLACE FUNCTION public.update_construction_budget()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE public.constructions
    SET budget = get_construction_budget_total(
        COALESCE(NEW.construction_uid, OLD.construction_uid)
    )
    WHERE uid = COALESCE(NEW.construction_uid, OLD.construction_uid);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_budget_update ON public.budgets;
CREATE TRIGGER trg_budget_update
    AFTER INSERT OR UPDATE OR DELETE ON public.budgets
    FOR EACH ROW
    EXECUTE FUNCTION public.update_construction_budget();

-- ******************** SCHEDULE STATE TRIGGER ********************
CREATE OR REPLACE FUNCTION public.check_schedule_deadline()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    deadline_date DATE;
BEGIN
    IF NEW.state != 'SOLVED' THEN
        BEGIN
            deadline_date := TO_DATE(NEW.deadline, 'DD/MM/YYYY');
            IF deadline_date < CURRENT_DATE THEN
                NEW.state := 'LATE';
            END IF;
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_schedule_deadline ON public.schedules;
CREATE TRIGGER trg_schedule_deadline
    BEFORE INSERT OR UPDATE ON public.schedules
    FOR EACH ROW
    EXECUTE FUNCTION public.check_schedule_deadline();

-- ******************** VERIFICATION ********************
SELECT 'Functions and triggers created successfully' as status;

-- ============================================================
-- 005-seed.sql
-- ============================================================

-- ============================================================
-- ConstructManager — Seed / Sample Data
-- Run after 004-functions.sql for testing purposes only
-- ============================================================

-- Add sample users (replace with real auth users)
INSERT INTO public.users (uid, name, email, admin, is_email_verified, role) VALUES
    ('demo-user-1', 'Иван Иванов', 'ivan@example.com', TRUE, TRUE, 'customer'),
    ('demo-user-2', 'Пётр Петров', 'petr@example.com', FALSE, TRUE, 'executor'),
    ('demo-user-3', 'Анна Сидорова', 'anna@example.com', FALSE, TRUE, 'contractor')
ON CONFLICT (uid) DO NOTHING;

-- Add sample constructions
INSERT INTO public.constructions (uid, title, address, type, stage, owner_uid, map_address, information) VALUES
    ('demo-constr-1', 'Ремонт офиса', 'ул. Ленина, 10', 'Офисный', 'ПОДГОТОВКА', 'demo-user-1', '55.7558,37.6173', 'Плановый ремонт офисного помещения'),
    ('demo-constr-2', 'Строительство дома', 'ул. Садовая, 25', 'Жилой', 'В_ИСПОЛНЕНИИ', 'demo-user-1', '55.7614,37.6249', 'Индивидуальный жилой дом'),
    ('demo-constr-3', 'Реконструкция склада', 'пр. Мира, 5', 'Промышленный', 'ЗАВЕРШЕНО', 'demo-user-1', '55.7500,37.6000', 'Складской комплекс завершен')
ON CONFLICT (uid) DO NOTHING;

-- Add sample budgets
INSERT INTO public.budgets (uid, construction_uid, title, description, value) VALUES
    ('demo-budg-1', 'demo-constr-1', 'Материалы', 'Закупка стройматериалов', 500000),
    ('demo-budg-2', 'demo-constr-1', 'Работа', 'Оплата рабочим', 300000),
    ('demo-budg-3', 'demo-constr-2', 'Фундамент', 'Заливка фундамента', 1500000),
    ('demo-budg-4', 'demo-constr-2', 'Кровля', 'Кровельные работы', 800000)
ON CONFLICT (uid) DO NOTHING;

-- Add sample schedules
INSERT INTO public.schedules (uid, construction_uid, title, start_date, deadline, state) VALUES
    ('demo-sched-1', 'demo-constr-1', 'Демонтаж', '15/05/2026', '01/06/2026', 'SOLVED'),
    ('demo-sched-2', 'demo-constr-1', 'Отделка', '15/06/2026', '01/08/2026', 'ON_SCHEDULE'),
    ('demo-sched-3', 'demo-constr-2', 'Фундаментные работы', '01/03/2026', '15/04/2026', 'LATE'),
    ('demo-sched-4', 'demo-constr-2', 'Возведение стен', '01/05/2026', '15/07/2026', 'ON_SCHEDULE')
ON CONFLICT (uid) DO NOTHING;

-- Add sample delays
INSERT INTO public.delays (uid, construction_uid, schedule_uid, title, reason, is_excusable, is_compensable, days, additional_info) VALUES
    ('demo-delay-1', 'demo-constr-2', 'demo-sched-3', 'Задержка поставки бетона', 'Срыв поставки поставщиком', TRUE, TRUE, 14, 'Поставщик не уложился в сроки по договору')
ON CONFLICT (uid) DO NOTHING;

-- (responsibilities seed data removed)

-- ============================================================
-- Manual steps required:
-- ============================================================
-- 1. Create Storage Bucket:
--    In Supabase Dashboard → Storage → Create bucket
--    Name: "construction-photos"
--    Public: YES
--    (or run: INSERT INTO storage.buckets (id, name, public)
--             VALUES ('construction-photos', 'construction-photos', true)
--             ON CONFLICT (id) DO NOTHING;)
--
-- 2. Enable Email Auth:
--    Supabase Dashboard → Authentication → Providers → Email
--
-- 3. Get API Keys:
--    Supabase Dashboard → Settings → API
--    Copy Project URL and anon/public key into the app.
-- ============================================================

SELECT 'ConstructManager database deployed successfully!' as result;
