"""
combine-sql.py

Combines all numbered SQL files from database/ (001-*.sql, 002-*.sql, etc.)
into a single self-contained database/deploy.sql ready for Supabase SQL Editor.

Usage:
    python scripts/combine-sql.py
    python scripts/combine-sql.py --skip-seed
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

from _common import Colors, log, project_root


def numbered_sql_files(database: Path) -> list[Path]:
    pattern = re.compile(r"^\d{3}-.+\.sql$")
    files = [f for f in sorted(database.iterdir()) if f.is_file() and pattern.match(f.name)]
    if not files:
        log("No numbered SQL files found in database/.", Colors.RED)
        raise SystemExit(1)
    return files


def combine(files: list[Path], output: Path, *, skip_seed: bool = False) -> None:
    parts: list[str] = [
        "-- ============================================================",
        "-- ConstructManager — Full Database Deployment",
        "-- Generated by scripts/combine-sql.py",
        "-- Run this entire file in Supabase SQL Editor to deploy",
        "-- the complete database schema, RLS policies, storage,",
        "-- functions, and seed data.",
        "-- ============================================================",
        "",
    ]

    for filepath in files:
        if skip_seed and "seed" in filepath.name.lower():
            log(f"  Skipping {filepath.name} (--skip-seed)", Colors.YELLOW)
            continue

        content = filepath.read_text(encoding="utf-8").strip()
        parts.append(f"-- ============================================================")
        parts.append(f"-- {filepath.name}")
        parts.append(f"-- ============================================================")
        parts.append("")
        parts.append(content)
        parts.append("")
        log(f"  Added {filepath.name}", Colors.GREEN)

    parts.append("-- ============================================================")
    parts.append("-- Manual steps required:")
    parts.append("-- ============================================================")
    parts.append("-- 1. Create Storage Bucket:")
    parts.append('--    In Supabase Dashboard \u2192 Storage \u2192 Create bucket')
    parts.append('--    Name: "construction-photos"')
    parts.append("--    Public: YES")
    parts.append("--    (or run: INSERT INTO storage.buckets (id, name, public)")
    parts.append("--             VALUES ('construction-photos', 'construction-photos', true)")
    parts.append("--             ON CONFLICT (id) DO NOTHING;)")
    parts.append("--")
    parts.append("-- 2. Enable Email Auth:")
    parts.append("--    Supabase Dashboard \u2192 Authentication \u2192 Providers \u2192 Email")
    parts.append("--")
    parts.append("-- 3. Get API Keys:")
    parts.append("--    Supabase Dashboard \u2192 Settings \u2192 API")
    parts.append("--    Copy Project URL and anon/public key into the app.")
    parts.append("-- ============================================================")
    parts.append("")
    parts.append("SELECT 'ConstructManager database deployed successfully!' as result;")
    parts.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8")
    log(f"Written {len(parts)} lines to {output}", Colors.CYAN)


def main() -> None:
    parser = argparse.ArgumentParser(description="Combine numbered SQL files into database/deploy.sql.")
    parser.add_argument("--skip-seed", action="store_true", help="Exclude 005-seed.sql from output.")
    args = parser.parse_args()

    root = project_root()
    database = root / "database"
    output = database / "deploy.sql"

    if not database.exists():
        log(f"database/ directory not found at {database}", Colors.RED)
        raise SystemExit(1)

    log("Scanning database/ for numbered SQL files...", Colors.CYAN)
    files = numbered_sql_files(database)

    log(f"Found {len(files)} files, combining into {output}...", Colors.CYAN)
    combine(files, output, skip_seed=args.skip_seed)

    log("Done. deploy.sql is ready for Supabase SQL Editor.", Colors.GREEN)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.")
    except Exception as e:
        print(f"\n{Colors.RED}{e}{Colors.RESET}")
        raise SystemExit(1)
